"""Improvement suggestions for the report.

Default path is deterministic and rule-based (no network). If an Anthropic key
is configured and ``use_llm`` is on, suggestions are generated by Claude instead,
falling back to the rule-based path on any error.
"""

from __future__ import annotations

import json
import logging
import os

from voc_analyzer import config

log = logging.getLogger(__name__)

# Default model for the report's summary/suggestions; override with VOC_LLM_MODEL
# (e.g. claude-opus-4-8 for higher-quality prose, or claude-haiku-4-5 to save cost).
MODEL = os.getenv("VOC_LLM_MODEL", "claude-sonnet-4-6")
MAX_SUGGESTIONS = 8

_SYSTEM = (
    "You are a senior product analyst writing for the product team that owns "
    "this product. You are given an aggregated Voice-of-Customer analysis of "
    "real social-media comments: sentiment, frequent keywords/phrases split by "
    "sentiment, and verbatim quotes.\n\n"
    "Identify the few DISTINCT underlying problems and strengths the data points "
    "to — synthesize themes, do not just restate individual words. Lean on the "
    "verbatim quotes: they reveal the specific issue behind a keyword (e.g. the "
    "keyword 'anc' may hide a complaint about auto-ANC; 'hinge' may indicate a "
    "structural defect compounded by warranty denials). A feature can be both a "
    "strength and a pain point — say so when the data shows it.\n\n"
    "Write 4-7 suggestions. Each must: name the concrete problem or opportunity, "
    "ground it in the evidence (cite the phrase/keyword or paraphrase a quote), "
    "and state a clear action. Order by apparent severity/frequency. Be specific "
    "and honest about uncertainty when the signal is thin.\n\n"
    "Respond ONLY with a JSON array of suggestion strings — no prose, no "
    "markdown, no surrounding object."
)

_SUMMARY_SYSTEM = (
    "You are a senior product analyst writing a short executive summary for the "
    "product team that owns this product. You are given an aggregated "
    "Voice-of-Customer analysis of real social-media comments: overall sentiment, "
    "frequent keywords/phrases split by sentiment, and verbatim quotes.\n\n"
    "Write 2-3 tight paragraphs (no headings, no bullet lists) a busy PM can read "
    "in 20 seconds: the overall mood and what's driving it, the clearest "
    "strengths, the clearest pain points, and — importantly — an honest caveat "
    "about the data when warranted (thin volume, off-topic or creator-praise "
    "noise, non-English comments, single-platform skew). Synthesize themes from "
    "the evidence; paraphrase quotes rather than inventing specifics, and say so "
    "plainly when the signal is too weak to conclude much.\n\n"
    "Respond with plain prose (markdown allowed) — no preamble like 'Here is', no "
    "JSON, no surrounding heading."
)


def suggest(analysis: dict, use_llm: bool = True) -> list[str]:
    """Return improvement suggestions for the given analysis dict."""
    if analysis.get("totals", {}).get("comments", 0) == 0:
        return []
    if use_llm and config.anthropic_enabled():
        try:
            return _suggest_llm(analysis)
        except Exception as exc:  # network, parsing, missing dep — degrade gracefully
            log.warning("LLM suggestions failed (%s); using rule-based fallback", exc)
    return _suggest_rule_based(analysis)


def summarize(analysis: dict, use_llm: bool = True) -> str:
    """Return an LLM-written executive summary, or ``""`` when unavailable.

    Unlike suggestions there is no rule-based fallback — a narrative summary is
    inherently an LLM feature, so without a key (or on any error) the section is
    simply omitted.
    """
    if analysis.get("totals", {}).get("comments", 0) == 0:
        return ""
    if use_llm and config.anthropic_enabled():
        try:
            return _summarize_llm(analysis)
        except Exception as exc:  # network, parsing, missing dep — omit gracefully
            log.warning("LLM summary failed (%s); omitting narrative summary", exc)
    return ""


def _suggest_rule_based(analysis: dict) -> list[str]:
    sentiment = analysis.get("sentiment", {})
    distribution = sentiment.get("distribution", {})
    total = sentiment.get("count", 0)
    negative = distribution.get("negative", 0)
    kbs = analysis.get("keywords_by_sentiment", {})
    neg = kbs.get("negative", {})
    pos = kbs.get("positive", {})
    neg_phrases = neg.get("phrases", [])
    neg_keywords = neg.get("keywords", [])
    pos_phrases = pos.get("phrases", [])
    pos_keywords = pos.get("keywords", [])

    def _mentions(n: int) -> str:
        return f"{n} mention" if n == 1 else f"{n} mentions"

    out: list[str] = []
    # Phrases are more specific than single words — surface them first.
    for phrase, count in neg_phrases[:3]:
        out.append(
            f"Recurring complaint about “{phrase}” ({_mentions(count)} in negative "
            f"comments) — investigate the root cause and address it."
        )
    for word, count in neg_keywords[: max(0, 5 - len(out))]:
        out.append(
            f"Users frequently raise “{word}” in negative comments "
            f"({_mentions(count)}) — check the representative quotes for the specifics."
        )
    if total and negative / total > 0.3:
        out.append(
            f"Negative sentiment is elevated ({negative}/{total} comments); "
            "prioritize the complaints above before new features."
        )
    strengths = [p for p, _ in pos_phrases[:2]] + [w for w, _ in pos_keywords[:3]]
    if strengths:
        out.append(f"Preserve current strengths users praise: {', '.join(strengths[:3])}.")
    if not out:
        out.append(
            "No strong negative signal detected; keep monitoring and reinforce "
            "the themes highlighted in positive comments."
        )
    return out[:MAX_SUGGESTIONS]


def _payload(analysis: dict) -> dict:
    """Compact projection of the analysis with only fields useful for suggestions."""
    sentiment = analysis.get("sentiment", {})
    representative = analysis.get("representative", {})
    kbs = analysis.get("keywords_by_sentiment", {})

    def _quotes(bucket: str) -> list[str]:
        out = []
        for q in representative.get(bucket, []):
            likes = q.get("likes")
            prefix = f"[{likes} likes] " if likes else ""
            out.append(prefix + q["text"])
        return out

    return {
        "product": analysis.get("product"),
        "keywords_searched": analysis.get("keywords"),
        "comments_analyzed": analysis.get("totals", {}).get("comments"),
        "platforms": analysis.get("platforms"),
        "mean_sentiment": sentiment.get("mean"),
        "sentiment_distribution": sentiment.get("distribution"),
        "negative_keywords": kbs.get("negative", {}).get("keywords"),
        "negative_phrases": kbs.get("negative", {}).get("phrases"),
        "positive_keywords": kbs.get("positive", {}).get("keywords"),
        "positive_phrases": kbs.get("positive", {}).get("phrases"),
        "negative_quotes": _quotes("negative"),
        "positive_quotes": _quotes("positive"),
    }


def _strip_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1] if "\n" in text else text
        text = text.rsplit("```", 1)[0]
    return text.strip()


def _suggest_llm(analysis: dict) -> list[str]:
    from anthropic import Anthropic

    client = Anthropic()
    message = client.messages.create(
        model=MODEL,
        max_tokens=2048,
        system=[{"type": "text", "text": _SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[
            {
                "role": "user",
                "content": (
                    "Here is the Voice-of-Customer analysis. Return the JSON array "
                    "of improvement suggestions.\n\n"
                    + json.dumps(_payload(analysis), ensure_ascii=False, indent=2)
                ),
            }
        ],
    )
    text = "".join(b.text for b in message.content if getattr(b, "type", None) == "text")
    data = json.loads(_strip_fences(text))
    if isinstance(data, dict):
        data = data.get("suggestions", [])
    return [str(item) for item in data][:MAX_SUGGESTIONS]


def _summarize_llm(analysis: dict) -> str:
    from anthropic import Anthropic

    client = Anthropic()
    message = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=[{"type": "text", "text": _SUMMARY_SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[
            {
                "role": "user",
                "content": (
                    "Here is the Voice-of-Customer analysis. Write the executive "
                    "summary.\n\n" + json.dumps(_payload(analysis), ensure_ascii=False, indent=2)
                ),
            }
        ],
    )
    return "".join(
        b.text for b in message.content if getattr(b, "type", None) == "text"
    ).strip()
