"""Improvement suggestions for the report.

Default path is deterministic and rule-based (no network). If an Anthropic key
is configured and ``use_llm`` is on, suggestions are generated by Claude instead,
falling back to the rule-based path on any error.
"""

from __future__ import annotations

import json
import logging
import os

from voc_analyzer import config

log = logging.getLogger(__name__)

# Default to the latest Claude model; override with VOC_LLM_MODEL (e.g. a cheaper
# claude-haiku-4-5 for high-volume runs).
MODEL = os.getenv("VOC_LLM_MODEL", "claude-opus-4-8")
MAX_SUGGESTIONS = 8

_SYSTEM = (
    "You are a senior product analyst. You are given an aggregated "
    "Voice-of-Customer analysis of social-media comments about a product. "
    "Produce concise, concrete, actionable product-improvement suggestions, "
    "each grounded in the data provided. Respond ONLY with a JSON array of short "
    "suggestion strings — no prose, no markdown, no surrounding object."
)


def suggest(analysis: dict, use_llm: bool = True) -> list[str]:
    """Return improvement suggestions for the given analysis dict."""
    if analysis.get("totals", {}).get("comments", 0) == 0:
        return []
    if use_llm and config.anthropic_enabled():
        try:
            return _suggest_llm(analysis)
        except Exception as exc:  # network, parsing, missing dep — degrade gracefully
            log.warning("LLM suggestions failed (%s); using rule-based fallback", exc)
    return _suggest_rule_based(analysis)


def _suggest_rule_based(analysis: dict) -> list[str]:
    sentiment = analysis.get("sentiment", {})
    distribution = sentiment.get("distribution", {})
    total = sentiment.get("count", 0)
    negative = distribution.get("negative", 0)
    neg_keywords = analysis.get("keywords_by_sentiment", {}).get("negative", [])
    pos_keywords = analysis.get("keywords_by_sentiment", {}).get("positive", [])

    out: list[str] = []
    for word, count in neg_keywords[:5]:
        out.append(
            f"Users frequently raise “{word}” in negative comments "
            f"({count} mentions) — investigate the root cause and address it."
        )
    if total and negative / total > 0.3:
        out.append(
            f"Negative sentiment is elevated ({negative}/{total} comments); "
            "prioritize the complaints above before new features."
        )
    if pos_keywords:
        strengths = ", ".join(word for word, _ in pos_keywords[:3])
        out.append(f"Preserve current strengths users praise: {strengths}.")
    if not out:
        out.append(
            "No strong negative signal detected; keep monitoring and reinforce "
            "the themes highlighted in positive comments."
        )
    return out[:MAX_SUGGESTIONS]


def _payload(analysis: dict) -> dict:
    """Compact projection of the analysis with only fields useful for suggestions."""
    sentiment = analysis.get("sentiment", {})
    representative = analysis.get("representative", {})
    return {
        "product": analysis.get("product"),
        "keywords": analysis.get("keywords"),
        "comments_analyzed": analysis.get("totals", {}).get("comments"),
        "mean_sentiment": sentiment.get("mean"),
        "sentiment_distribution": sentiment.get("distribution"),
        "negative_keywords": analysis.get("keywords_by_sentiment", {}).get("negative"),
        "positive_keywords": analysis.get("keywords_by_sentiment", {}).get("positive"),
        "negative_quotes": [q["text"] for q in representative.get("negative", [])],
        "positive_quotes": [q["text"] for q in representative.get("positive", [])],
    }


def _strip_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1] if "\n" in text else text
        text = text.rsplit("```", 1)[0]
    return text.strip()


def _suggest_llm(analysis: dict) -> list[str]:
    from anthropic import Anthropic

    client = Anthropic()
    message = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=[{"type": "text", "text": _SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[
            {"role": "user", "content": json.dumps(_payload(analysis), ensure_ascii=False)}
        ],
    )
    text = "".join(b.text for b in message.content if getattr(b, "type", None) == "text")
    data = json.loads(_strip_fences(text))
    if isinstance(data, dict):
        data = data.get("suggestions", [])
    return [str(item) for item in data][:MAX_SUGGESTIONS]
